//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeqAcc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int uid { get; set; }
        public int id { get; set; }
        public string password { get; set; }
        public int role { get; set; }
        public string name { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
