//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeqAcc.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int code_request { get; set; }
        public Nullable<int> telephone { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> id_street_pos { get; set; }
        public Nullable<int> id_area_pos { get; set; }
        public Nullable<int> id_street_vys { get; set; }
        public Nullable<int> id_area_vys { get; set; }
        public int number_card { get; set; }
        public string status { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
        public virtual Discount_card Discount_card { get; set; }
        public virtual Streeets Streeets { get; set; }
        public virtual Streeets Streeets1 { get; set; }
        public virtual Service_application Service_application { get; set; }
    }
}
